version: '3.2'
services:
  flask:
    image: trainer_image
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=postgresql://username:userpass@db:5433/pokemon
    depends_on:
      - db_pg
  
  db_pg:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: pokemon
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db_pg
    ports:
      - 8080:8080
